version: '3'

services:
#  redis:
#    # image: 'bitnami/redis:latest'
#    image: 'arm64v8/redis:latest'
#    container_name: redis
#    environment:
#      # ALLOW_EMPTY_PASSWORD is recommended only for development.
#      - ALLOW_EMPTY_PASSWORD=yes
#      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
#    ports:
#      - '6379:6379'
#    volumes:
#      - ./redis_data:/data
  flask:
    image: webapp-flask
    container_name: flask
    environment:
      - REDIS_SERVER=10.0.1.35
      - REDIS_PORT=13000
    build:
      context: .
      dockerfile: Dockerfile-flask
    ports:
      - '5001:5000'
    volumes:
      - "./src/:/app"
      - "./data/:/data"
