version: '3'

services:
  redis:
    # image: redislabs/redismod:latest
    image: redis/redis-stack:latest
    # image: myredis
    container_name: redis
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'
      - '8001:8001'
    volumes:
      - ./redis_data:/data

  flask:
    image: webapp-flask
    container_name: flask
    environment:
      - REDIS_SERVER=redis
      - REDIS_PORT=6379
      - INDEX_FILE_LOCATION=/data/index
      - CATEGORY_FILE_LOCATION=/data/CategoriesList.xml
      - PRODUCT_FILE_LOCATION=/data/product
      - PRODID_FILE_LOCATION=/data/prodid
      - PROCESSES=6
      - PYTHONBUFFERED=0
      - WRITE_JSON=true
      - DO_TITLE=false
      - FLASK_RUN_PORT=5001
    build:
      context: .
      dockerfile: Dockerfile-flask
    ports:
      - '5001:5001'
    volumes:
      - "./src/:/app"
      - "./data/:/data"
    depends_on:
      - redis
